### ISSUE TITLE
PR to official build

### ISSUE THREAD

**Issue by RedSparr0w** [Crobat4/pokeclicker-old#1]
Hey,

Any chance you would be willing to make PRs for the following things from your build to the main repo?:
- [x] Pokémon seen but not caught are now more noticeable in the Pokédex
- [x] Added setting to increase the game width
- [x] Alola/Timed/Location evolutions _(not sure if we've already added these or not)_
- [x] Some changes in the styles _(not sure what these are, but if readability etc)_
- [x] Added ID number to Pokémon list in the Profile menu

**Comment by Crobat4** [comment]
Hello.
Sure, I'll try to do them within the week.

**Comment by RedSparr0w** [comment]
Thanks for the PRs 👍
